---
# MongoDB Secret
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: infrastructure
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: fleetOS2024SecurePass!
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db
  namespace: infrastructure
  labels:
    app: mongo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
      - name: mongo-db
        image: mongo:7.0
        ports:
        - containerPort: 27017
          name: mongo
        envFrom:
        - secretRef:
            name: mongo-secret
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
        livenessProbe:
          exec:
            command:
              - mongosh
              - --eval
              - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
              - mongosh
              - --eval
              - "db.adminCommand('ping')"
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
      volumes:
      - name: mongodb-data
        emptyDir: {}  # Using emptyDir for demo - data won't persist across pod restarts
      - name: init-scripts
        configMap:
          name: mongo-init-scripts
          optional: true
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-db
  namespace: infrastructure
  labels:
    app: mongo-db
spec:
  type: ClusterIP
  selector:
    app: mongo-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      name: mongo
